# Generated by Django 5.0.4 on 2024-12-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_resumesubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='No Subject', max_length=100),
        ),
    ]
